# Generated by Django 3.1.1 on 2020-10-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='comment_time',
            field=models.DateTimeField(auto_now=True, verbose_name='评论时间'),
        ),
    ]
